### ISSUE TITLE
[BUG?] Random annotation with GRCh38

### ISSUE THREAD

**Issue by gambalab** [ZuchnerLab/Maverick#12]
Dear Maverick developers,

Thank you for providing this valuable tool. I was able to install and run Maverick with ease.

However, I encountered an issue with GRCh38 VCF files. The annotations in the two resulting files appear completely random. Neither the mutation effect nor the reported gene corresponds to the actual location. When I checked the coordinates on a genome browser, they mapped to different genes entirely. I haven't tested yet if converting the VCF to GRCh37 coordinates resolves the problem (probablily yes, because I have no problem with the provided test example that is HG19).

The command I used is:

`Maverick/InferenceScripts/runMaverick.sh -g ./mav_input/UD_AN001_P.vcf`

I've attached the VCF (renamed as `UD_AN001_P.txt `for GitHub upload) file containing mutations on chromosomes 1 and 2 for your reference. You can verify the issue by checking the annotations for the top 3-4 maverick  scoring mutations in a genome browser. Additionally, using the full VCF file leads to even more discrepancies. In some cases, the results report the wrong chromosome even though the position, reference allele, and alternate allele are correct and present in the original input VCF.

I would appreciate it if you could investigate this issue further.

Thank you for your time and support.

[UD_AN001_P.txt](https://github.com/user-attachments/files/16719631/UD_AN001_P.txt)

**Comment by gambalab** [comment]
Just a little update.. until ANNOVAR annotation everithyng if correct, after the groominh annotations become wrong.
I will attach here the cleaned vcf that I am using as a test.

Hope @mdanzi could investigate this issue further.

[UD_AN001_P.ontarget.annotated.dedup.filtered.vcf.gz](https://github.com/user-attachments/files/16732648/UD_AN001_P.ontarget.annotated.dedup.filtered.vcf.gz)

**Comment by gambalab** [comment]
UPDATE 3:
- if you liftover the vcf to HG19 nothing chenge, still you get wrong annotations.
- If mutations are splint into SNPs and INDELs and you run them separately, SNPs are processed correctly while INDELs no.

So the cause of the problem are INDELs that lead to problem in processing the vcf file. Unfortunately I am not an expet of python so I am not able to identify where the bug is.

Attached you can find mutations splitted by type.

[UD_AN001_P.ontarget.annotated.dedup.INDELs.filtered.vcf.gz](https://github.com/user-attachments/files/16733417/UD_AN001_P.ontarget.annotated.dedup.INDELs.filtered.vcf.gz)
[UD_AN001_P.ontarget.annotated.dedup.SNPs.filtered.vcf.gz](https://github.com/user-attachments/files/16733418/UD_AN001_P.ontarget.annotated.dedup.SNPs.filtered.vcf.gz)

**Comment by gambalab** [comment]
UPDATE 4:
I've located the bug.

Here's the breakdown:

1. A `_locations.txt `file is created based on the original VCF file.
2. `annovar/convert2annovar.pl` converts the VCF to an ANNOVAR-compatible `.avinput` format.
3. However, during this conversion, some mutations might be missing in the resulting `.avinput` file compared to the original VCF and `_locations.txt` file.
4. Later, in `groomAnnovarOutput.py` at `line 46`, a left join is performed between _locations.txt and the annotated file using line numbers. Since the `.avinput` file might be missing some mutations, their corresponding line numbers won't align with the complete `_locations.txt`. This mismatch leads to incorrect joining of annotation information.

The issue can be easily verified by comparing the number of lines in the `.avinput` file and the `_locations.txt` file for the provided UD_AN001_P.ontarget.annotated.dedup.INDELs.filtered.vcf.gz

**Comment by gambalab** [comment]
I can confirm that correcting aligning the `_locations.txt` file to the `.avinput`, the output become correct also for INDELs. I did a small R script that do that.

@mdanzi ..  When you will read these messages you should write a small patch in python to do this check and avoid this situations.

**Comment by mdanzi** [comment]
Hello @gambalab, 

Thank you for this excellent bug report and investigation! I completely agree with your diagnosis that the issue stems from a mismatch between the line numbers of the '_locations.txt' and '.avinput' files. Your investigation has made it clear to me that the way I set that up was very fragile. I have just pushed a change that gets rid of that system and just relies directly on Annovar. Please test out the new commit and let me know if it fixes your problem. 

However, when I looked into the issue, I didn't see the problem as being directly related to Indels per-se, but rather the 'RefCall' entries in your VCF. I think it was more of a gVCF than a regular VCF. Do you think that is possible as the problem or is there something specific to the Indels that is going wrong that I am not seeing? Hopefully the new change will take care of both problems, but always best to be sure. 

Best,
Matt

**Comment by gambalab** [comment]
Hi @mdanzi ,
thank you for the fix, I will test it on few vcf files I have and I will let you know.

> Hello @gambalab,
> However, when I looked into the issue, I didn't see the problem as being directly related to Indels per-se, but rather the 'RefCall' entries in your VCF. I think it was more of a gVCF than a regular VCF. Do you think that is possible as the problem or is there something specific to the Indels that is going wrong that I am not seeing? Hopefully the new change will take care of both problems, but always best to be sure.
> 
> Best, Matt

I agree that the issue was likely not directly related to INDELs. However, given that the VCF was generated using Deepvariant, it's possible that that problem is specific to it.

Anyway, it's great that you've resolved the issue, especially considering Deepvariant's increasing popularity as a variant caller, surpassing GATK4 in many applications.
