### ISSUE TITLE
tensorflow warnings

### ISSUE THREAD

**Issue by Wynandi** [ZuchnerLab/Maverick#13]
Dear developers,

I ran my first sample with Maverick successfully, receiving prioritization results.
Checking the logs I see warnings that might affect the results, but I am unable to understand the issue.

Could you assist me?

I attached the jobfiles.

Br,
Victoria

[job_err_32486_4294967294.txt_succesfulFirstrun.txt](https://github.com/user-attachments/files/17635084/job_err_32486_4294967294.txt_succesfulFirstrun.txt)
[firstrun.txt](https://github.com/user-attachments/files/17635085/firstrun.txt)
[job_out_32486_4294967294.txt](https://github.com/user-attachments/files/17635086/job_out_32486_4294967294.txt)

**Comment by mdanzi** [comment]
Hello Victoria,

From the job_err file, it looks like your conda environment might not be set up correctly (because of the 'conda: command not found' error) -- I'm not sure how things like this interact with the slurm back-end). This might have led to the wrong version of tensorflow getting used or something like that. To check whether these warnings are actually affecting anything or not, try running the example file in this repo and check if your outputs match the ones I had posted. If they do, you can safely ignore these warnings. 

Best,
Matt

**Comment by Wynandi** [comment]
Thank you for your response.

That line of Conda environment is familiar. It is nothing. I just added the activated Conda environment to the job I submitted to keep track of the environment used. In reality, I activate it before submitting the job. I should add a # to reduce confusion.

Regarding the example file this is a great idea but I had some issues with Annovar, it did not download the hg19 fasta file. I ran the example with hg38 instead of hg19. This was ok for me since my samples were hg38 anyway. To ensure my results are the same as yours I now need to fix hg19 too. I retried to download the hg19 but it failed.

Here is the example file error:
(maverick) vickuusi@hackman-2-20:/proj/pehackma/vickuusi/MAVERICK$ Maverick/InferenceScripts/runMaverick.sh Maverick/example/example.vcf
Starting Step 1: Get coding changes with Annovar
dos2unix: converting file Maverick/example/example.vcf to Unix format...
NOTICE: Finished reading 195 lines from VCF file
NOTICE: A total of 193 locus in VCF file passed QC threshold, representing 155 SNPs (74 transitions and 81 transversions) and 38 indels/substitutions
NOTICE: Finished writing 155 SNP genotypes (74 transitions and 81 transversions) and 38 indels/substitutions for 1 sample
NOTICE: The --geneanno operation is set to ON by default
NOTICE: Output files are written to Maverick/example/example.avinput.variant_function, Maverick/example/example.avinput.exonic_variant_function
NOTICE: Reading gene annotation from annovar/humandb/hg19_wgEncodeGencodeBasicV33lift37.txt ... Done with 93656 transcripts (including 34838 without coding sequence annotation) for 44591 unique genes
NOTICE: Processing next batch with 193 unique variants in 193 input lines
Error: FASTA sequence file annovar/humandb/hg19_wgEncodeGencodeBasicV33lift37Mrna.fa does not exist. Please use 'annotate_variation.pl --downdb wgEncodeGencodeBasicV33lift37 annovar/humandb' download the database.
No scorable variants found


It asks me to download it and I use this command in the annovar directory:
./annotate_variation.pl --downdb wgEncodeGencodeBasicV33lift37 humandb -build hg19



(maverick) vickuusi@hackman-2-20:/proj/pehackma/vickuusi/MAVERICK/annovar$ ./annotate_variation.pl --downdb wgEncodeGencodeBasicV33lift37 humandb -build hg19
NOTICE: Web-based checking to see whether ANNOVAR new version is available ... Done
NOTICE: Downloading annotation database http://hgdownload.cse.ucsc.edu/goldenPath/hg19/database/wgEncodeGencodeBasicV33lift37.txt.gz ... OK
NOTICE: Uncompressing downloaded files
NOTICE: Finished downloading annotation files for hg19 build version, with files saved at the 'humandb' directory
(maverick) vickuusi@hackman-2-20:/proj/pehackma/vickuusi/MAVERICK/annovar$ cd humandb/
(maverick) vickuusi@hackman-2-20:/proj/pehackma/vickuusi/MAVERICK/annovar/humandb$ ls
GRCh37_MT_ensGene.txt     genometrax-sample-files-gff  hg19_example_db_generic.txt  hg19_refGeneMrna.fa      hg19_refGeneWithVerMrna.fa              hg38_seq
GRCh37_MT_ensGeneMrna.fa  hg19_MT_ensGene.txt          hg19_example_db_gff3.txt     hg19_refGeneVersion.txt  hg19_wgEncodeGencodeBasicV33lift37.txt  hg38_wgEncodeGencodeBasicV33.txt
annovar_downdb.log        hg19_MT_ensGeneMrna.fa       hg19_refGene.txt             hg19_refGeneWithVer.txt  hg37_seq                                hg38_wgEncodeGencodeBasicV33Mrna.fa

There is no such file after "successful" download.

I also tried the manual instruction (./annotate_variation.pl -downdb -build hg38 seq humandb/hg38_seq/) but with hg37_seq, it creates only a log of failed downloads:

(maverick) vickuusi@hackman-2-20:/proj/pehackma/vickuusi/MAVERICK/annovar/humandb$ ls hg37_seq/
annovar_downdb.log

[annovar_downdb.log](https://github.com/user-attachments/files/17645784/annovar_downdb.log)


Upon researching this I noted the annovar_downdb.log for the hg38 was not perfect either.
NOTICE: Downloading annotation database http://hgdownload.cse.ucsc.edu/goldenPath/hg38/bigZips/chromFa.zip ... Failed
NOTICE: Downloading annotation database http://hgdownload.cse.ucsc.edu/goldenPath/hg38/bigZips/chromFa.tar.gz ... Failed
NOTICE: Downloading annotation database http://hgdownload.cse.ucsc.edu/goldenPath/hg38/bigZips/hg38.chromFa.tar.gz ... OK
NOTICE: Downloading annotation database http://hgdownload.cse.ucsc.edu/goldenPath/hg38/bigZips/hg38.fa.gz ... OK


So, there are some problems still with the installation. Is this anything familiar to you?
I also attached my notes on how I installed the program.

[Installation - not working for hg19, only for hg38.txt](https://github.com/user-attachments/files/17645910/Installation.-.not.working.for.hg19.only.for.hg38.txt)

**Comment by Wynandi** [comment]
Update:

I got more familiar with these and realized I only need to add this command:

./retrieve_seq_from_fasta.pl humandb/hg19_wgEncodeGencodeBasicV33lift37.txt -seqdir humandb/hg19_seq -format genericGene -outfile humandb/hg19_wgEncodeGencodeBasicV33lift37Mrna.fa 

Since I already had the .txt file needed to create the fasta.

Now I am running the example in the correct build. I will leave a last update if my results match yours and then this is settled.

Thank you very much.

**Comment by Wynandi** [comment]
Yes, results are matching. 
I will ignore the warnings in my analysis.

**Comment by mdanzi** [comment]
I'm glad to hear the warnings weren't affecting the results! I'll go ahead and mark this as closed. I hope the rest of your analysis goes smoothly!
