### ISSUE TITLE
failed to run

### ISSUE THREAD

**Issue by pickpingk** [ZuchnerLab/Maverick#2]
Hello
When I tried to run the software, some errors and warnings occurred. I have installed and configured the software according to the install requirements, and solved all dependency problems. The server I am using does not have a GPU, so step 2.1 is skipped. I The complete command and output have been placed in output.txt.
good luck
[output.txt](https://github.com/ZuchnerLab/Maverick/files/12435954/output.txt)

**Comment by mdanzi** [comment]
Hello, 

Thanks for your interest in Maverick! Sorry to hear about the difficulties you are having. Unfortunately, I get a 'Not Found' page when I click the output.txt file you linked. Could you try again or provide more details?

**Comment by pickpingk** [comment]
Dear Developer
I'm very sorry that the uploaded output.txt could not be opened, I uploaded the file again and hopefully it's working now.
Good luck!
[output.txt](https://github.com/ZuchnerLab/Maverick/files/12441756/output.txt)

**Comment by mdanzi** [comment]
Much better! Ok, I think there are a couple problems. The first issue is that you are using the '-g' parameter when executing 'runMaverick.sh'. That tells Annovar that the VCF is GRCh38, but the example vcf is GRCh37. So Annovar says all (or almost all) the variants have the wrong reference allele. Try again like this:
Maverick/InferenceScripts/runMaverick.sh Maverick/example/example.vcf 

The second issue seems to be with TensorFlow. It looks to me like you might have a newer version of it installed that is no longer compatible. Could you confirm for me which version of TF you have? I may need to revise the installation instructions if it is not working right. 

You also mentioned needing to debug dependency problems. Could you tell me more about that? I suspect that is related. 

Best,
Matt

**Comment by pickpingk** [comment]
Dear Developer
Thank you for your reply, I realized the problem by annotating the vcf of GRCh38 using annovar, so earlier I found the problem, so I was using Maverick/InferenceScripts/runMaverick.sh -g ... /vep_data/input/homo_sapiens_GRCh38.vcf command to re-run the program, and there is still an error, homo_sapiens_GRCh38.vcf is the example input given by the VEP software.
My configuration for maverick is following the installation instructions.
I put the program runtime information and tf version information in the output file
[output-GRCh38.txt](https://github.com/ZuchnerLab/Maverick/files/12442059/output-GRCh38.txt)
Good luck!

**Comment by mdanzi** [comment]
Hello again, 

Sorry for my delayed reply here. The problem should be fixed now in the updated INSTALL document instructions. Specifically, step 2.2 has been adjusted to assert the version of tensorflow that needs to be used:
pip install pandas matplotlib scikit-learn scipy biopython tensorflow==2.7 transformers tf-models-official==2.7

Try removing and re-setting up your conda environment and let me know if this fixes the problem.

**Comment by pickpingk** [comment]
Dear Developer
Thank you for your reply, I have reconfigured and used it according to your updated installation process and it works fine now, thanks!
