### ISSUE TITLE
when does the clinvar trainned used to pre-compute autosomal score?

### ISSUE THREAD

**Issue by zhouzaiwei** [ZuchnerLab/Maverick#4]
Hi Developer,
     I want to know when does the clinvar trainned used to pre-compute autosomal score? will the performance be improved if  join recent year ClinVar P/LP and B/LB variants to train?

**Comment by mdanzi** [comment]
Hello, 
I'm not sure I completely understand your question, but Maverick was trained on ClinVar data through the end of 2019 (the January 2020 pull of ClinVar). You can replicate this process with the files in the 'Notebooks' folder and can edit them to use more recent versions of ClinVar and re-train the system if you are interested (and ultimately generate new scores for the variants you are interested in). I am sure that the additional data would improve Maverick's performance somewhat, but this is not something that I plan to do in a regular fashion (as part of a regular release schedule or anything like that). 
Does that answer your question?

**Comment by zhouzaiwei** [comment]
thanks! you already answer my question.
