### ISSUE TITLE
Cannot download Maverick_resources.tar.gz - ERROR 403: Forbidden

### ISSUE THREAD

**Issue by manucpbon** [ZuchnerLab/Maverick#9]
Hello!

I am trying to install Maverick following the INSTALL file instructions, but I haven't been able to access the resources file.

When I try downloading Maverick_resources.tar.gz with `wget https://zuchnerlab.s3.amazonaws.com/VariantPathogenicity/MAVERICK/Maverick_resources.tar.gz` I get a 403 ERROR: Forbidden. I have also tried downloading it through Firefox and the MaverickInference.ipynb file on Google Colab, but both also return this same error.

 Is there another way can I get access to the Resources file?

Thanks in advance.

**Comment by mdanzi** [comment]
Sorry about that! The file accidentally got moved to cold storage. It should be fixed now. Let me know if you still get that error.
